Scheduler:
  Enable:
    type: checkbox
    value: false
    option: [ true, false ]
  NextRun: 1989-12-27 00:00:00
  Command: NKAS
  SuccessInterval:
    value: 0
    display: hide
  FailureInterval:
    value: 120
    display: hide
  ServerUpdate:
    value: 04:00
    display: hide
Client:
  Platform:
    value: adb
    option: [ adb, win ]
  Language:
    value: zh-CN
    option: [ zh-CN, en-US ]
Emulator:
  Serial:
    value: auto
    valuetype: str
  PackageName:
    value: com.proximabeta.nikke
    option: [ com.proximabeta.nikke, com.gamamobi.nikke, ]
  ScreenshotMethod:
    value: DroidCast
    option: [ DroidCast, ]
  ControlMethod:
    value: minitouch
    option: [ minitouch, ]
  AdbRestart: false
  ScreenshotInterval: 0.5
EmulatorInfo:
  Emulator:
    value: auto
    option: [
      auto,
      NoxPlayer,
      NoxPlayer64,
      BlueStacks4,
      BlueStacks5,
      BlueStacks4HyperV,
      BlueStacks5HyperV,
      LDPlayer3,
      LDPlayer4,
      LDPlayer9,
      MuMuPlayer,
      MuMuPlayerX,
      MuMuPlayer12,
      MEmuPlayer,
    ]
  name:
    value: null
    type: textarea
  path:
    value: null
    type: textarea
PCClient:
  Screens: false
  ScreenNumber:
    value: 0
    option: [ 0, 1, 2, 3, 4, 5 ]
  GameResolutionCompat:
    value: true
  CloseAutoHdr: true
  ScreenRotate: false
  GameWindowPosition:
    value: center
    option: [ center, left, right, topleft, topright ]
  Account:
    value: ''
  Password:
    value: ''
PCClientInfo:
  Client:
    value: intl
    option: [ intl, hmt ]
  AutoFillName: true
  LauncherPath:
    value: ''
    type: textarea
  LauncherTitleName:
    value: ''
  LauncherProcessName:
    value: ''
  GamePath:
    value: ''
    type: textarea
  GameTitleName:
    value: ''
  GameProcessName:
    value: ''
  ScreenshotInterval: 0.3
Optimization:
  AutoRedCircle: false
  OcrModelType:
    value: mobile
    option: [ mobile, server ]
  WhenTaskQueueEmpty:
    value: goto_main
    option: [ stay_there, goto_main, close_game ]
Reward:
  CollectSocialPoint: true
  CollectSpecialArenaPoint: false
  CollectRanking: true
DailyRecruit:
  EventFreeRecruit: true
  SocialPointRecruit: true
  Ordinary150GemRecruit: false
  SSRNotifyPush: false
  ScreenshotPath:
    value: ''
    type: textarea
SimulationRoom:
  QuickSimulation: true
  Immediately: false
Area:
  Difficulty:
    value: 'Level_1'
    option: [ 'Level_1', 'Level_2', 'Level_3','Level_4','Level_5' ]
  OnsetArea:
    value: A
    option: [ A, B, C ]
  EndingArea:
    value: A
    option: [ A, B, C ]
Overcome:
  OnlyToCompleteDailyMission: false
GeneralShop:
  enable: true
  priority:
    value: 'GRATIS > CORE_DUST_CASE > ORNAMENT'
    type: textarea
ArenaShop:
  enable: false
  priority:
    value: ''
    type: textarea
RubbishShop:
  priority:
    value: 'GEM > CORE_DUST_CASE'
    type: textarea
  bonePriority:
    value: ''
    type: textarea
Notification:
  WhenDailyTaskCompleted: false
  WhenDailyTaskCrashed: false
  WinOnePush: false
  OnePushConfig:
    type: textarea
    mode: yaml
    value: 'provider: null'
Daily:
  SendGift: false
  EnhanceEquipment: false
  CallReward: false
CollectionItems:
  Enable: false
  Priority:
    value: ''
    type: textarea
OpponentSelection:
  Enable: false
  SortingWeight:
    value: '{"Power":0.3, "CommanderLevel":0.2, "SynchroLevel":0.3, "Ranking":0.2}'
    type: textarea
  SelectionStrategy:
    value: 'Min'
    option: [ 'Max','Middle','Min' ]
Conversation:
  #QuickConsultation: false
  OnlyFavourite: false
  OnlyLogsNotMax: false
BlaAuth:
  UserAgent:
    value: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36'
    type: textarea
  Cookie:
    value: ''
    type: textarea
  XCommonParams:
    value: ''
    type: textarea
BlaDaily:
  Immediately: false
  Points:
    value: ''
    display: disabled
Coop:
  MatchDifficulty:
    value: 'Normal'
    option: [ 'Normal' ]
CDK:
  Extra: false
  Source:
    value: 'https://gamewith.jp/nikke/article/show/371014'
    type: textarea
    display: disabled
BlaExchange:
  Priority:
    value: 'Gem_×320 > Gem_×120 > Gem_×60 > Gem_×30 > Welcome_Gift_Core_Dust_×30'
    type: textarea
Event:
  Event:
    value: ''
    option: [
      'event_20251030',
      'event_20251016',
      'event_20250924',
      'event_20250904',
      'event_20250807',
      'event_20250716',
      'event_20250703s',
      'event_20250703l',
      'event_20250612'
    ]
    display: disabled
  LoginStamp: true
  Challenge: true
  Story: false
  StoryPart:
    value: 'Story_1'
    option: [
      'Story_1',
      'Story_2'
    ]
    display: disabled
  StoryDifficulty:
    value: 'Normal'
    option: [
      'Normal',
      'Hard'
    ]
    display: disabled
  Coop: false
  Shop: false
  ShopDelayList:
    value: 'TITLE'
    type: textarea
  Game: false
  GameStorySkip: false
  GameLoop: false
CheerStrategy:
  Enable: false
  Strategy:
    value: 'Most'
    option: [ 'Most','Few','Random' ]
Interception:
  Boss:
    value: 'Kraken'
    option: [ 'Kraken', 'Indivilia', 'Harvester', 'MirrorContainer', 'Ultra' ]
  AchieveLevel:
    value: 1
    option: [ 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
  QuickBattleOnly: false
  DropScreenshotPath:
    value: ''
    type: textarea
InterceptionTeam:
  Kraken:
    value: 1
    option: [ 1, 2, 3, 4, 5 ]
  Indivilia:
    value: 2
    option: [ 1, 2, 3, 4, 5 ]
  Harvester:
    value: 3
    option: [ 1, 2, 3, 4, 5 ]
  MirrorContainer:
    value: 4
    option: [ 1, 2, 3, 4, 5 ]
  Ultra:
    value: 5
    option: [ 1, 2, 3, 4, 5 ]
Overclock:
  # DisableFirst: false
  SkipRatioCheck: false
  AlwaysReselect: false
  ModifierList:
    value: "ENEMY_WEAPON_UP_3\nENEMY_ARMOR_UP_3\nENEMY_VITALS_UP_3\nNO_RECYCLING\nAGGRESSIVE_TACTICS\nRUSH_HOUR_3\nRELEVANT_PERSONNEL_ONLY"
    type: textarea
AutoTower:
  Enable:
    value: true
    display: disabled
SemiCombat:
  SkipStory:
    value: false
  FightQuickly:
    value: false
  MainStoryMark:
    value: false
BlaCDKManual:
  CDK:
    value: ''
    type: textarea
Highlights:
  AutoSwitch:
    value: true
    display: disabled
ScreenRotate:
  Orientation:
    value: 0
    option: [ 0, 1 ]
Synchro:
  UseBox:
    value: true
    display: disabled
Hosts:
  Action:
    value: 'Add'
    option: [ 'Add','Delete' ]
  Hosts:
    value: "# 通用\n18.155.202.10 cloud.nikke-kr.com\n43.132.85.192 nikke-en.com\n43.132.85.192 nikke-jp.com\n43.132.85.192 nikke-kr.com\n# 国际 Global\n43.152.186.163 global-lobby.nikke-kr.com\n43.152.186.163 global-match.nikke-kr.com\n# 日本 JP\n# 43.152.186.163 jp-lobby.nikke-kr.com\n# 43.152.186.163 jp-match.nikke-kr.com\n# 韩国 KR\n# 43.152.186.163 kr-lobby.nikke-kr.com\n# 43.152.186.163 kr-match.nikke-kr.com\n# 东南亚 SEA\n# 43.152.186.163 sea-lobby.nikke-kr.com\n# 43.152.186.163 sea-match.nikke-kr.com\n# 港澳台 HK/MC/TW\n# 43.152.186.163 hmt-lobby.nikke-kr.com\n# 43.152.186.163 hmt-match.nikke-kr.com\n# 北美 NA\n# 175.97.131.54 us-match.nikke-kr.com\n# 175.97.131.54 us-lobby.nikke-kr.com"
    type: textarea
SurfaceDaily:
  AutoPlace:
    value: true
  Heal:
    value: true
    display: disabled