Scheduler:
  Enable:
    type: checkbox
    value: false
    option: [ true, false ]
  NextRun: 1989-12-27 00:00:00
  Command: NKAS
  SuccessInterval:
    value: 0
    display: hide
  FailureInterval:
    value: 120
    display: hide
  ServerUpdate:
    value: 04:00
    display: hide
Emulator:
  Serial:
    value: auto
    valuetype: str
  PackageName:
    value: com.proximabeta.nikke
    option: [ com.proximabeta.nikke, com.gamamobi.nikke, ]
  Language:
    value: zh-cn
    option: [ zh-cn ]
  ScreenshotMethod:
    value: DroidCast
    option: [ DroidCast, ]
  ControlMethod:
    value: minitouch
    option: [ minitouch, ]
  AdbRestart: false
  ScreenshotInterval: 0.5
EmulatorInfo:
  Emulator:
    value: auto
    option: [
      auto,
      NoxPlayer,
      NoxPlayer64,
      BlueStacks4,
      BlueStacks5,
      BlueStacks4HyperV,
      BlueStacks5HyperV,
      LDPlayer3,
      LDPlayer4,
      LDPlayer9,
      MuMuPlayer,
      MuMuPlayerX,
      MuMuPlayer12,
      MEmuPlayer,
    ]
  name:
    value: null
    type: textarea
  path:
    value: null
    type: textarea
Optimization:
  AutoRedCircle: false
  OcrModelType:
    value: mobile
    option: [ mobile, server ]
  WhenTaskQueueEmpty:
    value: goto_main
    option: [ stay_there, goto_main, close_game ]
Reward:
  CollectSocialPoint: true
  CollectSpecialArenaPoint: true
  CollectRanking: true
DailyRecruit:
  EventFreeRecruit: true
  SocialPointRecruit: true
SimulationRoom:
  QuickSimulation: true
Area:
  Difficulty:
    value: 'Level_1'
    option: [ 'Level_1', 'Level_2', 'Level_3','Level_4','Level_5' ]
  OnsetArea:
    value: A
    option: [ A, B, C ]
  EndingArea:
    value: A
    option: [ A, B, C ]
Overcome:
  OnlyToCompleteDailyMission: false
GeneralShop:
  enable: true
  priority:
    value: 'GRATIS > CORE_DUST_CASE > ORNAMENT'
    type: textarea
ArenaShop:
  enable: false
  priority:
    value: ''
    type: textarea
RubbishShop:
  priority:
    value: 'GEM > CORE_DUST_CASE'
    type: textarea
  bonePriority:
    value: ''
    type: textarea
Notification:
  WhenDailyTaskCompleted: false
  WhenDailyTaskCrashed: false
  OnePushConfig:
    type: textarea
    mode: yaml
    value: 'provider: null'
Daily:
  SendGift: false
  EnhanceEquipment: false
  CallReward: false
CollectionItems:
  NIKKE:
    value: 'All'
    option: [ 'All','Laplace','Frima','Diesel','Exia' ]
OpponentSelection:
  Enable: false
  SortingWeight:
    value: '{"Power":0.3, "CommanderLevel":0.2, "SynchroLevel":0.3, "Ranking":0.2}'
    type: textarea
  SelectionStrategy:
    value: 'Min'
    option: [ 'Max','Middle','Min' ]
Conversation:
  #QuickConsultation: false
  OnlyFavourite: false
  OnlyLogsNotMax: false
BlaAuth:
  UserAgent:
    value: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36'
    type: textarea
  Cookie:
    value: ''
    type: textarea
  XCommonParams:
    value: ''
    type: textarea
BlaDaily:
  PostID:
    value: ''
    valuetype: str
  CommentID:
    value: ''
    valuetype: str
  Points:
    value: ''
    display: disabled
Coop:
  MatchDifficulty:
    value: 'Normal'
    option: [ 'Normal' ]
CDK:
  Extra: false
  Source:
    value: 'https://gamewith.jp/nikke/article/show/371014'
    type: textarea
    display: disabled
BlaExchange:
  Priority:
    value: 'Gem_×320 > Gem_×120 > Gem_×60 > Gem_×30 > Welcome_Gift_Core_Dust_×30'
    type: textarea
Event:
  Event:
    value: ''
    option: [
      'event_20250807',
      'event_20250716',
      'event_20250703s',
      'event_20250703l',
      'event_20250612'
    ]
    display: disabled
  LoginStamp: true
  Challenge: true
  Story: false
  StoryPart:
    value: 'Story_1'
    option: [
      'Story_1',
      'Story_2'
    ]
    display: disabled
  StoryDifficulty:
    value: 'Normal'
    option: [
      'Normal',
      'Hard'
    ]
    display: disabled
  Coop: false
  Shop: false
  ShopDelayList:
    value: 'TITLE'
    type: textarea
  Game: false
CheerStrategy:
  Enable: false
  Strategy:
    value: 'Most'
    option: [ 'Most','Few','Random' ]
Interception:
  DropScreenshotPath:
    value: ''
    type: textarea
Overclock:
  # DisableFirst: false
  SkipRatioCheck: false
  AlwaysReselect: false
  ModifierList:
    value: "ENEMY_WEAPON_UP_3\nENEMY_ARMOR_UP_3\nENEMY_VITALS_UP_3\nNO_RECYCLING\nAGGRESSIVE_TACTICS\nRUSH_HOUR_3\nRELEVANT_PERSONNEL_ONLY"
    type: textarea
TowerDaemon:
  Enable:
    value: true
    display: disabled
CombatDaemon:
  Enable:
    value: false
    display: disabled
EventDaemon:
  Enable:
    value: false
    display: disabled
