# ==================== Reward ====================

Reward:
  Scheduler:
    Enable: true

DailyRecruit:
  Scheduler:
    Enable: false

Commission:
  Scheduler:
    Enable: false

RookieArena:
  Scheduler:
    Enable: false

SpecialArena:
  Scheduler:
    Enable: false

ChampionArena:
  Scheduler:
    Enable: false

Conversation:
  Scheduler:
    Enable: false

SimulationRoom:
  Scheduler:
    Enable: false

TribeTower:
  Scheduler:
    Enable: false

Daily:
  Scheduler:
    Enable: false

RubbishShop:
  Scheduler:
    Enable: false

MissionPass:
  Scheduler:
    Enable: false

Liberation:
  Scheduler:
    Enable: false

DailyGift:
  Scheduler:
    Enable: false

WeeklyGift:
  Scheduler:
    Enable: false

MonthlyGift:
  Scheduler:
    Enable: false

BlaDaily:
  Scheduler:
    Enable: false

BlaCDK:
  Scheduler:
    Enable: false

BlaExchange:
  Scheduler:
    Enable: false

Event:
  Scheduler:
    Enable: false

Event2:
  Scheduler:
    Enable: false

Coop:
  Scheduler:
    Enable: false

SoloRaid:
  Scheduler:
    Enable: false

UnionRaid:
  Scheduler:
    Enable: false

Synchro:
  Scheduler:
    Enable: false

Recycling:
  Scheduler:
    Enable: false