# ==================== NKAS ====================

Restart:
  Scheduler:
    Enable:
      value: true
      display: disabled
    SuccessInterval: 0
    FailureInterval: 0
    ServerUpdate: 04:00

# ==================== Reward ====================

Reward:
  Scheduler:
    Enable:
      value: true
      type: lock
    SuccessInterval: 720-720
    FailureInterval: 720-720
    ServerUpdate: 04:00, 20:00

Commission:
  Scheduler:
    SuccessInterval: 720-720
    FailureInterval: 720-720

BlaCDK:
  Scheduler:
    ServerUpdate: 04:00, 16:00

MissionPass:
  Scheduler:
    ServerUpdate: 04:00, 20:00
