# ==================== NKAS ====================

NKAS:
  menu: 'collapse'
  page: 'setting'
  tasks:
    NKAS:
      - Client
      - Optimization
      - Notification
    Emulator:
      - Emulator
      - EmulatorInfo
    PCClient:
      - PCClientInfo
      - PCClient
    Restart:
      - Scheduler

# ==================== Reward ====================

Reward:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Reward:
      - Scheduler
      - Reward
    Destruction:
      - Scheduler
    Mailbox:
      - Scheduler

# ==================== Daily ====================

Daily:
  menu: 'collapse'
  page: 'setting'
  tasks:
    DailyRecruit:
      - Scheduler
      - DailyRecruit
    Daily:
      - Scheduler
      - Daily
    MissionPass:
      - Scheduler
    Conversation:
      - Scheduler
      - Conversation
    Shop:
      - Scheduler
      - GeneralShop
      - ArenaShop
    RubbishShop:
      - Scheduler
      - RubbishShop
    EpisodeViewing:
      - Scheduler

# ==================== Outpost ====================

Outpost:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Commission:
      - Scheduler
      - CollectionItems
    Liberation:
      - Scheduler
    Synchro:
      - Scheduler
      - Synchro
    Recycling:
      - Scheduler
    OutpostStory:
      - Scheduler

# ==================== Ark ====================

Ark:
  menu: 'collapse'
  page: 'setting'
  tasks:
    SimulationRoom:
      - Scheduler
      - SimulationRoom
      - Area
    Overclock:
      - Scheduler
      - Overclock
    TribeTower:
      - Scheduler
      - Overcome
    Interception:
      - Scheduler
      - Interception
      - InterceptionTeam
    RookieArena:
      - Scheduler
      - RookieArena
      - OpponentSelection
    SpecialArena:
      - Scheduler
      - SpecialArena
      - OpponentSelection
    ChampionArena:
      - Scheduler
      - CheerStrategy

# ==================== LimitedTimeEvent ====================

LimitedTimeEvent:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Coop:
      - Scheduler
      - Coop
    SoloRaid:
      - Scheduler
    UnionRaid:
      - Scheduler

# ==================== StoryEvent ====================

StoryEvent:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Event:
      - Scheduler
      - EventInfo
      - StoryStage
      - Event
    Event2:
      - Scheduler
      - EventInfo
      - StoryStage
      - Event

# ==================== Surface ====================

Surface:
  menu: 'collapse'
  page: 'setting'
  tasks:
    SurfaceDaily:
      - Scheduler
      - SurfaceDaily

# ==================== Blablalink ====================

Blablalink:
  menu: 'collapse'
  page: 'setting'
  tasks:
    BlaAuth:
      - BlaAuth
    BlaDaily:
      - Scheduler
      - BlaDaily
    BlaCDK:
      - Scheduler
      - CDK
    BlaExchange:
      - Scheduler
      - BlaExchange

# ==================== Gift ====================

Gift:
  menu: 'collapse'
  page: 'setting'
  tasks:
    StepUpGift:
      - Scheduler
    DailyGift:
      - Scheduler
    WeeklyGift:
      - Scheduler
    MonthlyGift:
      - Scheduler

# ==================== Tool ====================

Tool:
  menu: 'collapse'
  page: 'tool'
  tasks:
    AutoTower:
      - AutoTower
    SemiCombat:
      - SemiCombat
    Highlights:
      - Highlights
    BlaCDKManual:
      - BlaCDKManual
    ScreenRotate:
      - ScreenRotate
    UpdateHosts:
      - Hosts
