# ==================== NKAS ====================

NKAS:
  menu: 'collapse'
  page: 'setting'
  tasks:
    NKAS:
      - Client
      - Optimization
      - Notification
    Emulator:
      - Emulator
      - EmulatorInfo
    PCClient:
      - PCClientInfo
      - PCClient
    Restart:
      - Scheduler

# ==================== Reward ====================

Reward:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Reward:
      - Scheduler
      - Reward
    Destruction:
      - Scheduler
    Commission:
      - Scheduler
      - CollectionItems
    Mailbox:
      - Scheduler

# ==================== Daily ====================

Daily:
  menu: 'collapse'
  page: 'setting'
  tasks:
    DailyRecruit:
      - Scheduler
      - DailyRecruit
    Daily:
      - Scheduler
      - Daily
    MissionPass:
      - Scheduler
    Liberation:
      - Scheduler
    Conversation:
      - Scheduler
      - Conversation
    Shop:
      - Scheduler
      - GeneralShop
      - ArenaShop
    RubbishShop:
      - Scheduler
      - RubbishShop

# ==================== Ark ====================

Ark:
  menu: 'collapse'
  page: 'setting'
  tasks:
    SimulationRoom:
      - Scheduler
      - SimulationRoom
      - Area
    Overclock:
      - Scheduler
      - Overclock
    TribeTower:
      - Scheduler
      - Overcome
    Interception:
      - Scheduler
      - Interception
      - InterceptionTeam
    RookieArena:
      - Scheduler
      - OpponentSelection
    SpecialArena:
      - Scheduler
      - OpponentSelection
    ChampionArena:
      - Scheduler
      - CheerStrategy

# ==================== LimitedTimeEvent ====================

LimitedTimeEvent:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Coop:
      - Scheduler
      - Coop
    SoloRaid:
      - Scheduler
    UnionRaid:
      - Scheduler

# ==================== StoryEvent ====================

StoryEvent:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Event:
      - Scheduler
      - Event
    Event2:
      - Scheduler
      - Event

# ==================== Blablalink ====================

Blablalink:
  menu: 'collapse'
  page: 'setting'
  tasks:
    BlaAuth:
      - BlaAuth
    BlaDaily:
      - Scheduler
      - BlaDaily
    BlaCDK:
      - Scheduler
      - CDK
    BlaExchange:
      - Scheduler
      - BlaExchange

# ==================== Gift ====================

Gift:
  menu: 'collapse'
  page: 'setting'
  tasks:
    StepUpGift:
      - Scheduler
    DailyGift:
      - Scheduler
    WeeklyGift:
      - Scheduler
    MonthlyGift:
      - Scheduler

# ==================== Tool ====================

Tool:
  menu: 'collapse'
  page: 'tool'
  tasks:
    AutoTower:
      - AutoTower
    SemiCombat:
      - SemiCombat
    SemiEvent:
      - SemiEvent
    BlaCDKManual:
      - BlaCDKManual
