# ==================== NKAS ====================

NKAS:
  - Emulator
  - Optimization
  - Notification

Restart:
  - Scheduler

# ==================== Reward ====================

Reward:
  - Scheduler
  - Reward

Destruction:
  - Scheduler

Commission:
  - Scheduler
  - CollectionItems

Mailbox:
  - Scheduler

# ==================== Daily ====================

DailyRecruit:
  - Scheduler
  - DailyRecruit

Daily:
  - Scheduler
  - Daily

MissionPass:
  - Scheduler

Liberation:
  - Scheduler

Conversation:
  - Scheduler
  - Conversation

Shop:
  - Scheduler
  - GeneralShop
  - ArenaShop

RubbishShop:
  - Scheduler
  - RubbishShop

SimulationRoom:
  - Scheduler
  - Area

TribeTower:
  - Scheduler
  - Overcome

RookieArena:
  - Scheduler
  - OpponentSelection

SpecialArena:
  - Scheduler
  - OpponentSelection

ChampionArena:
  - Scheduler
  - CheerStrategy

Interception:
  - Scheduler

Coop:
  - Scheduler
  - Coop

Event:
  - Scheduler
  - Event

Event2:
  - Scheduler
  - Event

SoloRaid:
  - Scheduler
  - SoloRaid

# ==================== Blablalink ====================

BlaAuth:
  - BlaAuth

BlaDaily:
  - Scheduler
  - BlaDaily

BlaCDK:
  - Scheduler
  - CDK

BlaExchange:
  - Scheduler
  - BlaExchange

# ==================== Tools ====================

TowerDaemon:
  - Scheduler

CombatDaemon:
  - Scheduler

EventDaemon:
  - Scheduler

# ==================== Gift ====================

DailyGift:
  - Scheduler

WeeklyGift:
  - Scheduler

MonthlyGift:
  - Scheduler
