Deploy:
  Git:
    Repository: https://gitee.com/megumiss/NIKKEAutoScript
    Branch: master
    GitExecutable: ./toolkit/Git/mingw64/bin/git.exe
    GitProxy: null
    SSLVerify: true
    AutoUpdate: true

  Python:
    PythonExecutable: ./toolkit/python.exe
    PypiMirror: https://mirrors.aliyun.com/pypi/simple
    InstallDependencies: true
    RequirementsFile: requirements.txt

  Adb:
    AdbExecutable: ./toolkit/Lib/site-packages/adbutils/binaries/adb.exe
    ReplaceAdb: true
    AutoConnect: true
    InstallUiautomator2: true

  Update:
    EnableReload: true
    CheckUpdateInterval: 5
    AutoRestartTime: 03:50

  Webui:
    WebuiHost: localhost
    WebuiPort: 12271
