Deploy:
  Git:
    Repository: http://github.com/takagisanmie/NIKKEAutoScript
    Branch: master
    GitExecutable: /usr/bin/git
    GitProxy: http://tbox12:20171
    AutoUpdate: true

  Python:
    PythonExecutable: ./VENV/bin/python
    RequirementsFile: requirements.txt

  Adb:
    AdbExecutable: /usr/bin/adb
    ReplaceAdb: true
    AutoConnect: true
    InstallUiautomator2: true

  Update:
    EnableReload: true
    CheckUpdateInterval: 5
    AutoRestartTime: 03:50

  Webui:
    WebuiHost: localhost
    WebuiPort: 12271




