Deploy:
  Git:
    Repository: https://github.com/megumiss/NIKKEAutoScript
    Branch: master
    GitExecutable: ./toolkit/Git/mingw64/bin/git.exe
    GitProxy: null
    AutoUpdate: true

  Python:
    PythonExecutable: ./toolkit/python.exe
    RequirementsFile: requirements.txt

  Adb:
    AdbExecutable: ./toolkit/android-platform-tools/adb.exe
    ReplaceAdb: true
    AutoConnect: true
    InstallUiautomator2: true

  Update:
    EnableReload: true
    CheckUpdateInterval: 5
    AutoRestartTime: 03:50

  Webui:
    WebuiHost: localhost
    WebuiPort: 12271
